# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
cache: cocoapods
rvm: 2.2.2
osx_image: xcode8

podfile: Example/Podfile

before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild test -workspace Example/StyleDecorator.xcworkspace -scheme StyleDecorator-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
